### ISSUE TITLE
Refactoring package and Domain

### ISSUE THREAD

**Issue by khsrla9806** [depromeet/praise-push-server#61]
## 💡 Description
- 패키지 구조를 전반적으로 리펙토링할 필요성을 느낌

    - 현재 클린 아키텍처에서 벗어나는 부분들이 몇 가지 있음.

- 클린 아키텍처를 위해 Domain(자바 순수 객체)과 JPA 객체를 분리하여 중간에 Mapper를 두었다.

    - 여기서 발생되는 문제점은 Mapper를 거치면 `JPA -> Domain` 객체 변환 과정에서 JPA의 Lazy 로딩과 같은 기능을 사용할 수 없게 된 것
    - 관련 내용을 정리해둔 PR : #46 

- **오늘 해커톤에서 만났을 때 한번 논의하고 해결 보면 좋을거 같아서 이슈 만들어두었습니다~**

<br>

## 🏃🏻‍♂️ Process
- [x] 헥사고날 아키텍처 점검
    - #70 
- [x] slack이나 s3, ncp 등 외부적인 것은 별도 infrastructure 또는 external 등으로 빼는 작업
- [x] JPA Entity와 Domain 관련 내용 확정 후 리펙토링 진행

<br>

## 🔗 Reference
- [reference]()

<br>

**Comment by mywnajsldkf** [comment]
+) 지난 회의에서 이야기 나온 것처럼 slack이나 s3, ncp 등 외부적인 것은 별도 infrastructure 또는 external 등으로 빼는 작업을 진행해야 합니다!
